### ISSUE TITLE
Crash when added to server 

### ISSUE THREAD

**Issue by cauliflower69** [Arcfalt/ExtendAHand#1]
http://pastebin.com/ALbVBdpR

**Comment by Arcfalt** [comment]
Thanks for the report, will look in to it as soon as I get a chance.

**Comment by Arcfalt** [comment]
Alright, ended up being a larger issue than I thought it would be, but it should be resolved now. I've given it some testing after my fixes and found no server crashes, and both items work when using a dedicated server. Thanks again for the report, and if anything further pops up feel free to open a new issue! :)
